name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  alert:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: danhellem/github-actions-issue-to-work-item@master
        env:
          ado_token: "${{522rtbikw3jggroewflyz7tz632syvsx6iecqljkl4c655kd4gvq}}"
          github_token: "${{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}}"
          ado_organization: "PowerPlatform12121"
          ado_project: "Test123"
          ado_area_path: "Test123"
          ado_iteration_path: "Test123"
          ado_wit: "Issue"
          ado_new_state: "New"
          ado_active_state: "Active"
          ado_close_state: "Closed"
          ado_bypassrules: true
          log_level: 100
