- name: GitHub Issues to Azure DevOps
  # You may pin to the exact commit or the version.
  # uses: danhellem/github-actions-issue-to-work-item@3072da42abf94ebe4c7778c57fb4af06db341c72
  uses: danhellem/github-actions-issue-to-work-item@v2.2
